### ISSUE TITLE
真机调试有问题

### ISSUE THREAD

**Issue by niuxinghua** [ecomfe/echarts-for-weixin#190]
## 提问前应该做的事

请确保提问前做了以下事，将完成的项目的 `[]` 改为 `[x]`：

- [x] 我已通读过 [README](https://github.com/ecomfe/echarts-for-weixin/blob/master/README.md)
- [x] 我已阅读过 [FAQ](https://github.com/ecomfe/echarts-for-weixin/issues?utf8=%E2%9C%93&q=is%3Aissue+label%3Afaq+)

## 需提供的信息
Cannot read property 'width' of undefined;at pages/monitorInfo/Info onReady function;at api request success callback function
TypeError: Cannot read property 'width' of undefined
    at e.value ([publib]:6:5058)
    at Object.K_.measureText (weapp:///echarts/echarts.js:1:248331)
    at Te (weapp:///echarts/echarts.js:1:21093)
    at ge (weapp:///echarts/echarts.js:1:18720)
    at De (weapp:///echarts/echarts.js:1:21056)
    at Ae (weapp:///echarts/echarts.js:1:21154)
    at ve (weapp:///echarts/echarts.js:1:18883)
    at me (weapp:///echarts/echarts.js:1:18836)
    at dl (weapp:///echarts/echarts.js:1:96124)
    at ED.getLabelInterval (weapp:///echarts/echarts.js:1:355865)
将符合项的 `[]` 改为 `[x]`，并补充需要的信息：

### 简单描述问题：
真机调试有bug，模拟器没问题

### 预期效果：
（如有需要请提供预期的图）

### 实际效果：

（如有需要请提供截图）

### 复现环境：
- [] 在微信开发工具中存在该问题
- [ ] 在真机上存在该问题

**Comment by Ovilia** [comment]
是不是容器没有高度宽度？
