### ISSUE TITLE
wepy引入echarts报错 [Error] Error: 找不到模块: zrender/container/Group

### ISSUE THREAD

**Issue by zhouweiming** [ecomfe/echarts-for-weixin#315]
使用了  https://github.com/ecomfe/echarts-for-weixin/issues/7  中的方式引入

执行 wepy build --watch

```
➜  iov-we-app git:(master) ✗ wepy build --watch
[12:08:08] [编译] 入口: src/app.wpy
[12:08:09] [写入] JSON: dist/app.json
[12:08:09] [编译] 组件: src/components/counter.wpy
[12:08:09] [编译] 组件: src/components/group.wpy
[12:08:09] [编译] 组件: src/components/groupitem.wpy
[12:08:09] [编译] 组件: src/components/list.wpy
[12:08:10] [编译] 组件: src/components/panel.wpy
[12:08:10] [编译] 组件: src/components/wepy-list.wpy
[12:08:10] [拷贝] JSON: src/ec-canvas/ec-canvas.json
[12:08:10] [编译] Other: src/ec-canvas/ec-canvas.wpy
[12:08:10] [删除] 配置: dist/ec-canvas/ec-canvas.json
[WARN]: Some file is greater than 500KB, babel ignored it.
[12:08:10] [拷贝] HTML: src/index.template.html
[12:08:10] [编译] 页面: src/pages/index.wpy
[12:08:10] [写入] JSON: dist/pages/index.json
[12:08:10] [编译] 页面: src/pages/map.wpy
[12:08:10] [写入] JSON: dist/pages/map.json
[12:08:10] [写入] JS  : dist/app.js
[12:08:10] [写入] JS  : dist/components/counter.js
[12:08:11] [写入] JS  : dist/components/group.js
[12:08:11] [写入] JS  : dist/components/groupitem.js
[12:08:11] [写入] JS  : dist/components/list.js
[12:08:11] [写入] JS  : dist/components/panel.js
[12:08:11] [写入] JS  : dist/components/wepy-list.js
[12:08:11] [写入] WXML: dist/ec-canvas/ec-canvas.wxml
[12:08:11] [写入] JS  : dist/ec-canvas/ec-canvas.js
[12:08:11] [写入] JS  : dist/ec-canvas/wx-canvas.js
[12:08:11] [写入] JS  : dist/mixins/test.js
[12:08:11] [写入] WXML: dist/pages/index.wxml
[12:08:11] [写入] JS  : dist/pages/index.js
[12:08:11] [写入] WXML: dist/pages/map.wxml
[12:08:11] [写入] JS  : dist/pages/map.js
[12:08:11] [写入] JS  : dist/store/actions/counter.js
[12:08:11] [写入] JS  : dist/store/actions/index.js
[12:08:11] [写入] JS  : dist/store/index.js
[12:08:11] [写入] JS  : dist/store/reducers/counter.js
[12:08:11] [写入] JS  : dist/store/reducers/index.js
[12:08:11] [写入] JS  : dist/store/types/counter.js
[12:08:11] [写入] JS  : dist/store/types/index.js
[Error] Error: 找不到模块: zrender/container/Group
被依赖于: /Users/www/iov-we-app/src/ec-canvas/echarts.js。
请尝试手动执行 npm install zrender/container/Group 进行安装。
    at /usr/local/lib/node_modules/wepy-cli/lib/compile-script.js:124:27
    at String.replace (<anonymous>)
    at Object.resolveDeps (/usr/local/lib/node_modules/wepy-cli/lib/compile-script.js:46:21)
    at /usr/local/lib/node_modules/wepy-cli/lib/compile-script.js:278:27
    at process._tickCallback (internal/process/next_tick.js:68:7)
    at Function.Module.runMain (internal/modules/cjs/loader.js:746:11)
    at startup (internal/bootstrap/node.js:238:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:572:3)
[12:08:11] [写入] WXSS: dist/ec-canvas/ec-canvas.wxss
[12:08:11] [写入] WXSS: dist/app.wxss
[12:08:11] [写入] WXSS: dist/components/counter.wxss
[12:08:11] [写入] WXSS: dist/components/group.wxss
[12:08:11] [写入] WXSS: dist/components/groupitem.wxss
[12:08:11] [写入] WXSS: dist/components/list.wxss
[12:08:11] [写入] WXSS: dist/components/panel.wxss
[12:08:11] [写入] WXSS: dist/components/wepy-list.wxss
[12:08:11] [写入] WXSS: dist/pages/index.wxss
[12:08:11] [写入] WXSS: dist/pages/map.wxss
[12:08:11] [信息] 开始监听文件改动。


```

## 引入方式：

1. 将ec-canvas目录拷贝到src目录下
2. 在ec-canvas目录中添加ec-canvas.wpy文件：
   ```
     import wepy from 'wepy'
     import WxCanvas from '../ec-canvas/wx-canvas'
     import * as echarts from '../ec-canvas/echarts'
     export default class EcCanvas extends wepy.component {
   ```
3. 在页面中使用：
   ```
     import ecCanvas from '../ec-canvas/ec-canvas'
     import * as echarts from '../ec-canvas/echarts'
     export default class Map extends wepy.page {
   ```

wepy --version: 1.7.3
已关闭es6转es5
```
	"setting": {
		"urlCheck": false,
		"es6": false,
		"postcss": false,
		"minified": false,
		"newFeature": true
	},
```

**Comment by hrpc** [comment]
我在echarts官网下载的最新的源代码版本，还是在编译的时候报你这个错误呢

**Comment by zhouweiming** [comment]
@hrpc 要确保是混淆后的，哪个版本无所谓

**Comment by shenyiling** [comment]
@zhouweiming 混淆好的代码什么意思啊
