### ISSUE TITLE
将图表实例绑定到this上供其它函数使用报错

### ISSUE THREAD

**Issue by HEYEggplant** [ecomfe/echarts-for-weixin#378]
## 提问前应该做的事

请确保提问前做了以下事，将完成的项目的 `[]` 改为 `[x]`：

- [] 我已通读过 [README](https://github.com/ecomfe/echarts-for-weixin/blob/master/README.md)
- [] 我已阅读过 [FAQ](https://github.com/ecomfe/echarts-for-weixin/issues?utf8=%E2%9C%93&q=is%3Aissue+label%3Afaq+)

## 需提供的信息

将符合项的 `[]` 改为 `[x]`，并补充需要的信息：

### 简单描述问题：
获取图表实例

### 实际效果：
？？？
（如有需要请提供截图）

框架： wepy

### 复现环境：
- [x] 在微信开发工具中存在该问题
- [x] 在真机上存在该问题

代码: 

```init() {
        this.ecComponent = this.$wxpage.selectComponent('#mychart-kline')
        this.ecComponent.init((canvas, width, height) => {
          // 获取组件的 canvas、width、height 后的回调函数
          // 在这里初始化图表
          const chart = echarts.init(canvas, null, {
            width: width,
            height: height
          })
          setOption(chart)

          **// 将图表实例绑定到 this 上，可以在其他成员函数（如 dispose）中访问
          this.chart = chart**

          // 注意这里一定要返回 chart 实例，否则会影响事件处理等
          return chart
        })
      },


控制台报错： 
thirdScriptError
Maximum call stack size exceeded; [Component] Event Handler Error @ pages/testchart#bound 
RangeError: Maximum call stack size exceeded
    at e (http://127.0.0.1:36623/appservice/__dev__/WAService.js:19:9148)
    at e (http://127.0.0.1:36623/appservice/__dev__/WAService.js:19:9404)
    at e (http://127.0.0.1:36623/appservice/__dev__/WAService.js:19:9336)
    at e (http://127.0.0.1:36623/appservice/__dev__/WAService.js:19:9404)
    at e (http://127.0.0.1:36623/appservice/__dev__/WAService.js:19:9404)
    at e (http://127.0.0.1:36623/appservice/__dev__/WAService.js:19:9336)
    at e (http://127.0.0.1:36623/appservice/__dev__/WAService.js:19:9404)
    at e (http://127.0.0.1:36623/appservice/__dev__/WAService.js:19:9404)
    at e (http://127.0.0.1:36623/appservice/__dev__/WAService.js:19:9336)
    at e (http://127.0.0.1:36623/appservice/__dev__/WAService.js:19:9404)

**Comment by dtboy1995** [comment]
您把chart换个名字就好比如this._chart
因为和内部的变量冲突导致了循环调用了
