### ISSUE TITLE
 ECharts 在线定制 下载后的包，替换以后效果完全没问题，但是点击图表总有报错

### ISSUE THREAD

**Issue by xiaoxing92** [ecomfe/echarts-for-weixin#438]
效果是完全没问题的，但是一直有报错，我下载官网的完整版包替换了也一样报错！

thirdScriptError
this.chart._zr.handler.proxy.processGesture is not a function;at undefined page touchEnd function
TypeError: this.chart._zr.handler.proxy.processGesture is not a function
    at K.touchEnd (http://127.0.0.1:38781/appservice/ec-canvas/ec-canvas.js:125:38)
    at K.M (http://127.0.0.1:38781/appservice/__dev__/WAService.js:1:831860)
    at xt (http://127.0.0.1:38781/appservice/__dev__/WAService.js:1:856434)
    at http://127.0.0.1:38781/appservice/__dev__/WAService.js:1:866876
    at Function.<anonymous> (http://127.0.0.1:38781/appservice/__dev__/WAService.js:1:867271)
    at http://127.0.0.1:38781/appservice/__dev__/WAService.js:1:831222
    at http://127.0.0.1:38781/appservice/__dev__/WAService.js:1:457767
    at n (http://127.0.0.1:38781/appservice/__dev__/WAService.js:1:277588)
    at e (http://127.0.0.1:38781/appservice/appservice?t=1548040516383:1126:20972)
    at r.registerCallback.t (http://127.0.0.1:38781/appservice/appservice?t=1548040516383:1126:21157)

**Comment by Ovilia** [comment]
因为新加的功能 ECharts 还没发版。解决方法：1）使用这个项目的 https://github.com/ecomfe/echarts-for-weixin/blob/master/ec-canvas/echarts.js；或者 2）本项目回退到 https://github.com/ecomfe/echarts-for-weixin/tree/a066b406f8b98c525fbbd71eef77ea6182fe4899

**Comment by jijingsong** [comment]
我也是报这个错，现在解决了吗

**Comment by LJJCherry** [comment]
我也是报这个错，现在解决了吗

**Comment by LJJCherry** [comment]
我也遇到了这个问题

**Comment by fengxiaobai2019** [comment]
https://github.com/ecomfe/echarts-for-weixin/blob/master/ec-canvas/echarts.js 我用这个全量文件，那我还上官网定制组件干啥，就是因为定制后下载的文件才出问题
