### ISSUE TITLE
使用echart渲染图表正常，但是渲染后页面上再使用setData方法时，报错(开发者工具中报错，实体机体验正常)

### ISSUE THREAD

**Issue by xiaotan0305** [ecomfe/echarts-for-weixin#440]
## 提问前应该做的事

请确保提问前做了以下事，将完成的项目的 `[]` 改为 `[x]`：

- [x] 我已通读过 [README](https://github.com/ecomfe/echarts-for-weixin/blob/master/README.md)
- [] 我已阅读过 [FAQ](https://github.com/ecomfe/echarts-for-weixin/issues?utf8=%E2%9C%93&q=is%3Aissue+label%3Afaq+)

## 需提供的信息

将符合项的 `[]` 改为 `[x]`，并补充需要的信息：

### 简单描述问题：
使用echart渲染图表正常，但是渲染后页面上再使用setData方法时，报错(开发者工具中报错，实体机体验正常)，感觉是与开发者工具中setData冲突，同事开发其他页面有相同问题。
报错信息如下：
VM3105:1 thirdScriptError
Converting circular structure to JSON; [Component] Event Handler Error @ pages/fangjia/togetherSearch/togetherSearch#bound toggleChartDetail
TypeError: Converting circular structure to JSON
    at JSON.stringify (<anonymous>)
    at Object.t [as send] (http://127.0.0.1:28335/appservice/appservice?t=1548065633067:15467:1032)
    at Object.e [as publish] (http://127.0.0.1:28335/appservice/appservice?t=1548065633067:15467:20078)
    at Object.publish (http://127.0.0.1:28335/appservice/__dev__/WAService.js:1:117505)
    at ze (http://127.0.0.1:28335/appservice/__dev__/WAService.js:1:262085)
    at Object.vdSyncBatch (http://127.0.0.1:28335/appservice/__dev__/WAService.js:1:552484)
    at t.flushSendingData (http://127.0.0.1:28335/appservice/__dev__/WAService.js:1:638048)
    at a.value (http://127.0.0.1:28335/appservice/__dev__/WAService.js:1:659990)
    at e.value (http://127.0.0.1:28335/appservice/__dev__/WAService.js:1:641558)
    at o._updateCb (http://127.0.0.1:28335/appservice/__dev__/WAService.js:1:594811)
### 预期效果：
开发者工具中不报错。
（如有需要请提供预期的图）

### 实际效果：

![image](https://user-images.githubusercontent.com/12965330/51470207-37408100-1dae-11e9-8847-40d155aa66e1.png)

（如有需要请提供截图）
代码截图：
> 目录结构：

![image](https://user-images.githubusercontent.com/12965330/51470252-5808d680-1dae-11e9-8817-dd3b34a2056c.png)
> wxml: 

![image](https://user-images.githubusercontent.com/12965330/51470288-6b1ba680-1dae-11e9-90ef-edd932a927dc.png)
> json:

![image](https://user-images.githubusercontent.com/12965330/51470330-84bcee00-1dae-11e9-9536-3bce1a1aed18.png)

> js:

* data设置
![image](https://user-images.githubusercontent.com/12965330/51470360-a0c08f80-1dae-11e9-8d76-faa4c6dc708c.png)
*  异步请求数据后初始化echarts
![image](https://user-images.githubusercontent.com/12965330/51470409-c2217b80-1dae-11e9-8576-559634fd2e6f.png)
* 初始化后台在异步响应用户操作使用setData方法就会报错，尝试不使用return chart不会报错，但是图表交互就会失效，使用return chart后其他响应用户操作的异步setData都会报错
![image](https://user-images.githubusercontent.com/12965330/51470550-2a705d00-1daf-11e9-8b1e-e973becb932b.png)

![image](https://user-images.githubusercontent.com/12965330/51470712-a9fe2c00-1daf-11e9-9ba0-8e65de7d5e18.png)

### 复现环境：
- [x] 在微信开发工具中存在该问题
- [] 在真机上存在该问题

**Comment by xiaotan0305** [comment]
我的反馈没法复现么，为啥没有大神回复，好伤心。

**Comment by fuxingjun** [comment]
怎么直接关闭了,请问如何解决的,我也遇到了

**Comment by fuxingjun** [comment]
> 怎么直接关闭了,请问如何解决的,我也遇到了

不需要响应式的数据不要放在data里面，更不要直接赋值而不使用setData。。。一点经验，仅供参考
