### ISSUE TITLE
dispose方法报错：Cannot read property 'hide' of undefined

### ISSUE THREAD

**Issue by mtozhk** [ecomfe/echarts-for-weixin#454]
## 提问前应该做的事

请确保提问前做了以下事，将完成的项目的 `[]` 改为 `[x]`：

- [x] 我已通读过 [README](https://github.com/ecomfe/echarts-for-weixin/blob/master/README.md)
- [x] 我已阅读过 [FAQ](https://github.com/ecomfe/echarts-for-weixin/issues?utf8=%E2%9C%93&q=is%3Aissue+label%3Afaq+)

### 简单描述问题：
执行dispose方法时，报错Cannot read property 'hide' of undefined
已经更新了新版echart.js。开发工具里，以及iphone真机上测试，同样都报错。

### 复现环境：
- [x] 在微信开发工具中存在该问题
- [x] 在真机上存在该问题

**Comment by mtozhk** [comment]
补充一下，用现在官方微信小程序的lazyloading示例，同样会报此错。

错误信息如下：
VM2028:1 thirdScriptError
Cannot read property 'hide' of undefined; [Component] Event Handler Error @ pages/lazyLoad/index#bound dispose
TypeError: Cannot read property 'hide' of undefined
    at Lv.hide (http://127.0.0.1:11810/appservice/ec-canvas/echarts.js:22:603093)
    at i.dispose (http://127.0.0.1:11810/appservice/ec-canvas/echarts.js:22:610329)
    at http://127.0.0.1:11810/appservice/ec-canvas/echarts.js:22:351601
    at Array.forEach (<anonymous>)
    at d (http://127.0.0.1:11810/appservice/ec-canvas/echarts.js:22:1663)
    at ls.FT.dispose (http://127.0.0.1:11810/appservice/ec-canvas/echarts.js:22:351562)
    at z.dispose (http://127.0.0.1:11810/appservice/pages/lazyLoad/index.js:157:18)
    at Object.r.safeCallback (http://127.0.0.1:11810/appservice/__dev__/WAService.js:1:746848)
    at http://127.0.0.1:11810/appservice/__dev__/WAService.js:1:887706
    at f (http://127.0.0.1:11810/appservice/__dev__/WAService.js:1:890945)

**Comment by hsw409328** [comment]
Cannot read property 'hide' of undefined;at pages/analysis/index onPullDownRefresh function;at api request success callback function
TypeError: Cannot read property 'hide' of undefined
    at Lv.hide (http://127.0.0.1:52549/appservice/ec-canvas/echarts.js:22:603093)
    at i.dispose (http://127.0.0.1:52549/appservice/ec-canvas/echarts.js:22:610329)
    at vs (http://127.0.0.1:52549/appservice/ec-canvas/echarts.js:22:87344)
    at hs (http://127.0.0.1:52549/appservice/ec-canvas/echarts.js:22:85127)
    at ls.FT.setOption (http://127.0.0.1:52549/appservice/ec-canvas/echarts.js:22:345361)
    at ls.FT.clear (http://127.0.0.1:52549/appservice/ec-canvas/echarts.js:22:351421)
    at r.setPieChartChildOption (http://127.0.0.1:52549/appservice/pages/analysis/index.js:341:11)
    at Function.success (http://127.0.0.1:52549/appservice/pages/analysis/index.js:307:20)
    at Object.success (http://127.0.0.1:52549/appservice/__dev__/WAService.js:3:14159)
    at c.<anonymous> (http://127.0.0.1:52549/appservice/__dev__/WAService.js:10:15121)

**Comment by hsw409328** [comment]
官方有人回答吗？还是已经不更新了？

**Comment by hsw409328** [comment]
// tooltip: {
      //   trigger: 'item',
      //   formatter: "{b}：{c}元"
      // },  

注释掉就没事

**Comment by cjackeroo** [comment]
> ```
>   // tooltip: {
>   //   trigger: 'item',
>   //   formatter: "{b}：{c}元"
>   // },  
> ```
> 注释掉就没事

没找到这段啊

**Comment by hsw409328** [comment]
@cjackeroo  我是因为tooltip导致

**Comment by Jack-Lo** [comment]
官方能处理一下这个问题吗？？？

**Comment by Liuliu73** [comment]
同样遇到这个问题，请问有解决了吗 ？注释掉tooltip也没作用
