### ISSUE TITLE
echart在线压缩版本，树形图文字标签position不起作用，文字全在屏幕上方

### ISSUE THREAD

**Issue by xingzhisuozai930** [ecomfe/echarts-for-weixin#575]
echart在线压缩版本，树形图文字标签position不起作用，文字全在屏幕上方，非压缩版本正常，但是会报错
this.chart._zr.handler.proxy.processGesture is not a function;at undefined page touchEnd function
TypeError: this.chart._zr.handler.proxy.processGesture is not a function
    at ye.touchEnd (http://127.0.0.1:42887/appservice/components/echarts/ec-canvas/ec-canvas.js:125:38)
    at ye.D (WAService.js:1:1252070)
    at Qe (WAService.js:1:1270436)
    at WAService.js:1:1282978
    at Function.<anonymous> (WAService.js:1:1283373)
    at WAService.js:1:1251386
    at WAService.js:1:719414
    at WAService.js:1:392339
    at e (http://127.0.0.1:42887/appservice/appservice?t=1573659020341:2521:20972)
    at r.registerCallback.t (http://127.0.0.1:42887/appservice/appservice?t=1573659020341:2521:21157)

**Comment by xingzhisuozai930** [comment]
![echart](https://user-images.githubusercontent.com/57719726/68778840-aef9d800-066e-11ea-9af7-34d53f817d7e.PNG)
