### ISSUE TITLE
在使用tree图表样式时，symbol配置成图片，不支持

### ISSUE THREAD

**Issue by tian-jie** [ecomfe/echarts-for-weixin#903]
## 提问前应该做的事

请确保提问前做了以下事，将完成的项目的 `[]` 改为 `[x]`：

- [x] 我已通读过 [README](https://github.com/ecomfe/echarts-for-weixin/blob/master/README.md)
- [x] 我已阅读过 [FAQ](https://github.com/ecomfe/echarts-for-weixin/issues?utf8=%E2%9C%93&q=is%3Aissue+label%3Afaq+)

## 需提供的信息

将符合项的 `[]` 改为 `[x]`，并补充需要的信息：

### 简单描述问题：
在使用tree图表样式时，symbol配置成图片，不支持
https://echarts.apache.org/zh/option.html#series-tree.symbol
在echarts官网example可以显示成图片，但模拟器上提示错误：
```
Image is not defined;at setTimeout callback function
ReferenceError: Image is not defined
    at Object.loadImage (http://127.0.0.1:64569/appservice/ec-canvas/echarts.js:32:2843)
    at Zo (http://127.0.0.1:64569/appservice/ec-canvas/echarts.js:40:14947)
    at http://127.0.0.1:64569/appservice/ec-canvas/echarts.js:40:193541
    at tv (http://127.0.0.1:64569/appservice/ec-canvas/echarts.js:40:193953)
    at t._doPaintEl (http://127.0.0.1:64569/appservice/ec-canvas/echarts.js:40:323141)
    at x (http://127.0.0.1:64569/appservice/ec-canvas/echarts.js:40:322475)
    at p (http://127.0.0.1:64569/appservice/ec-canvas/echarts.js:40:322772)
    at t._doPaintList (http://127.0.0.1:64569/appservice/ec-canvas/echarts.js:40:322868)
    at t._paintList (http://127.0.0.1:64569/appservice/ec-canvas/echarts.js:40:321141)
    at t.refresh (http://127.0.0.1:64569/appservice/ec-canvas/echarts.js:40:320281)(env: Windows,mp,1.06.2303220; lib: 2.10.2)
```

### 预期效果：
![image](https://user-images.githubusercontent.com/25471485/230926820-dabb269e-330e-4bad-bd4f-57c5a597940a.png)

### 实际效果：
![image](https://user-images.githubusercontent.com/25471485/230926866-a94e02ae-93dd-4f06-aed3-a749b7f446ce.png)

### 复现环境：
- [x] 在微信开发工具中存在该问题
- [] 在真机上存在该问题

**Comment by tian-jie** [comment]
同时尝试了path，可以画图，但还是默认区域被自动填充成默认的颜色，不支持换颜色
![image](https://user-images.githubusercontent.com/25471485/230927725-308be3e6-62cf-42a9-98a8-586dd5a21c72.png)
